/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remotegpuAco.h"

bool_t
xdr_input_data (XDR *xdrs, input_data *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_int (xdrs, &objp->st_nNodes))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->st_distMat_h.st_distMat_h_val, (u_int *) &objp->st_distMat_h.st_distMat_h_len, 1000000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_rho))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_alpha))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_beta))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_Q))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->st_nAnts))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_maxIterations))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_convergenceNo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_nThreads))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->st_nAnts);
			IXDR_PUT_LONG(buf, objp->st_maxIterations);
			IXDR_PUT_LONG(buf, objp->st_convergenceNo);
			IXDR_PUT_LONG(buf, objp->st_nThreads);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_int (xdrs, &objp->st_nNodes))
			 return FALSE;
		 if (!xdr_array (xdrs, (char **)&objp->st_distMat_h.st_distMat_h_val, (u_int *) &objp->st_distMat_h.st_distMat_h_len, 1000000,
			sizeof (float), (xdrproc_t) xdr_float))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_rho))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_alpha))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_beta))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->st_Q))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->st_nAnts))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_maxIterations))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_convergenceNo))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->st_nThreads))
				 return FALSE;
		} else {
			objp->st_nAnts = IXDR_GET_LONG(buf);
			objp->st_maxIterations = IXDR_GET_LONG(buf);
			objp->st_convergenceNo = IXDR_GET_LONG(buf);
			objp->st_nThreads = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->st_nNodes))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->st_distMat_h.st_distMat_h_val, (u_int *) &objp->st_distMat_h.st_distMat_h_len, 1000000,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_rho))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_alpha))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_beta))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_Q))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->st_nAnts))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->st_maxIterations))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->st_convergenceNo))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->st_nThreads))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output_data (XDR *xdrs, output_data *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->st_bestTour_h.st_bestTour_h_val, (u_int *) &objp->st_bestTour_h.st_bestTour_h_len, 101,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_bestGraphLength))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->st_elapsedTime))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->st_iterNo))
		 return FALSE;
	return TRUE;
}
