/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMOTEGPUACO_H_RPCGEN
#define _REMOTEGPUACO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input_data {
	int st_nNodes;
	struct {
		u_int st_distMat_h_len;
		float *st_distMat_h_val;
	} st_distMat_h;
	float st_rho;
	float st_alpha;
	float st_beta;
	float st_Q;
	int st_nAnts;
	int st_maxIterations;
	int st_convergenceNo;
	int st_nThreads;
};
typedef struct input_data input_data;

struct output_data {
	struct {
		u_int st_bestTour_h_len;
		int *st_bestTour_h_val;
	} st_bestTour_h;
	float st_bestGraphLength;
	float st_elapsedTime;
	int st_iterNo;
};
typedef struct output_data output_data;



#define RPCGPUACOPROG 22855
#define RPCGPUACOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPCGPUACO 1
extern  output_data * rpcgpuaco_1(input_data *, CLIENT *);
extern  output_data * rpcgpuaco_1_svc(input_data *, struct svc_req *);
extern int rpcgpuacoprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPCGPUACO 1
extern  output_data * rpcgpuaco_1();
extern  output_data * rpcgpuaco_1_svc();
extern int rpcgpuacoprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_data (XDR *, input_data*);
extern  bool_t xdr_output_data (XDR *, output_data*);
extern  bool_t xdr_input_data (XDR *, input_data*);
extern  bool_t xdr_output_data (XDR *, output_data*);

#else /* K&R C */
extern bool_t xdr_input_data ();
extern bool_t xdr_output_data ();
extern bool_t xdr_input_data ();
extern bool_t xdr_output_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMOTEGPUACO_H_RPCGEN */
